- name: Distribute SSH key
  hosts: "*"
  remote_user: ike
  tasks:
    - include_vars: general.yml
    - name: creating .ssh directory
      file:
        path: "~/.ssh"
        mode: "0755"
        state: directory
    - name: copy pub key to servers
      copy:
        src: "~/.ssh/{{ssh_key_file}}.pub"
        dest: "~/.ssh/authorized_keys"
        mode: "0644"
        force: no
